version: "3.8"
services:
  
  emqx:
    container_name: emqx
    image: emqx/emqx:4.3.2
    restart: always
    ports:
      - ${emqxdashport}:18083
      - 8083:8083
    environment:
      #listener.tcp.external.max_connections 
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
      