version: "3.8"

volumes:
  vol-emqx-data:
    name: om-emqx-data
  vol-emqx-etc:
    name: om-emqx-etc
  vol-emqx-log:
    name: om-emqx-log

services:

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment: 
      TZ: "America/Bogota"
      MONGO_INITDB_ROOT_USERNAME: "devuser"
      MONGO_INITDB_ROOT_PASSWORD: "devpassword"
    volumes:
      - /mongodata:/data/db
    ports:
      - 27017:27017
  
  emqx:
    container_name: emqx
    image: emqx/emqx:4.3.2
    restart: always
    ports:
      - 18083:18083
      - 8083:8083

    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

    environment:
      EMQX_NAME: om-emqx
      EMQX_HOST: 127.0.0.1

      TZ: "America/Bogota"

      # DEFAULT DASH PSW      
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "emqxdashpass"

      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
    
      